CREATE SCHEMA `webshop` DEFAULT CHARACTER SET utf8;
CREATE TABLE `webshop`.`products` (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(15,5) UNSIGNED NULL,
  PRIMARY KEY (`id`));
